# Site wide configuration
title: "Artineering"
locale: en-US
description: "Rendering, in  style!"
copyright: © 2020 Artineering OÜ
#remote_theme: mmistakes/so-simple-theme
baseurl: # the subpath of your site, e.g. "/blog"
url: https://artineering.io
logo: /images/logo.png
logo-flat: /images/logo-flat.svg
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 175
mathjax: true
google_fonts:
  - name: "Lato"
    weights: "300,400,400i,700"
  - name: "Nanum Brush Script"
    weights: "400"
  - name: "Josefin Sans"
    weights: "700"
google_tag_manager: GTM-N5D7T4C
google_analytics_anon: UA-142029611-4
disqus:
  shortname: artineering
twitter:
  username: notpainted

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /blog/:categories/:title
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /news/page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/blog/"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - source
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-paginate

# Collections
collections:
  main:
    output: true
    permalink: /:slug/
  mnprdocs:
    output: true
    permalink: /software/MNPRX/docs/:slug/
  publications:
    output: true
    permalink: /:collection/:title/
  software:
    output: true
    permalink: /:collection/:title/
  styles:
    output: true
    permalink: /:collection/:title/
  seminars:
    output: true
    permalink: /:collection/:title/
  blog:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/


# Front Matter Defaults
defaults:
  # posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  # projects defaults
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: page
      comments: true
      share: true
  # default social card
  - scope:
      path: ""
    values:
      image:
        path: /images/cards/default.jpg


# Site Author
author:
  name: Artineering
  picture: /images/logo.jpg
  email: hello@artineering.io

# Twitter SEO
twitter:
  card: summary_large_image
  username: artineering

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/artineering
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://www.instagram.com/artineering.io/
    icon: fab fa-instagram
  - title: Facebook
    url: https://www.facebook.com/artineering/
    icon: fab fa-facebook-square
  - title: LinkedIn
    url: https://www.linkedin.com/company/artineering/
    icon: fab fa-linkedin
  - title: Github
    url: https://github.com/artineering-io/
    icon: fab fa-github-square
  - title: Youtube
    url: https://www.youtube.com/c/artineering
    icon: fab fa-youtube-square
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square
#  - title: Vimeo
#    url: https://vimeo.com/santiagomontesdeoca
#    icon: fab fa-vimeo-square
